services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memorynews
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432